export{gameLength,pos2}
import{Team} from"./player_generator.js"
export{chicagoBulls,newYorkKnicks,sanAntonioSpurs,milwaukeeBucks,somersetSpartans,freeAgents}

let gameLength = 2880
let pos2 = 0
let shotClock=24
let teamOneScore = 0
let teamTwoScore = 0


// constructor(city,teamName,shortName,primaryColor,secondaryColor,highColor,logo)
let newYorkKnicks = new Team('New York','Knicks','NYK',"rgb(19, 69, 204)","rgb(227, 138, 23)","rgb(174, 193, 245)",'url("images/knicks_logo.png")');
let chicagoBulls = new Team('Chicago','Bulls','CHI',"rgb(186, 24, 24)","black","rgba(243, 144, 144, 0.657)",'url("images/bulls_logo.png")');
let sanAntonioSpurs = new Team('San Antonio','Spurs','SAS','black','gray','rgb(180, 180, 180)',"url('images/spurs_logo.png')" )
let milwaukeeBucks = new Team('Milwaukee','Bucks','MIL','rgb(38,78,54)','rgb(223,210,175)','rgb(177, 212, 143)',"url('images/bucks_logo.png')" )
let somersetSpartans = new Team('Somerset','Spartans','SOM','rgb(103,19,11)','rgb(237,192,56)','rgb(204, 78, 67)',"url('images/spartans_logo.png')" )
let freeAgents = new Team('Free Agent','Players','FA','rgb(103,19,11)','rgb(237,192,56)','rgb(204, 78, 67)',)


//Team One

chicagoBulls.roster = [
    {name:'Giannis Antetokounmpo',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:95,pRat_offOverall:86,pRat_closeShot:95, pRat_midShot:83, pRat_longShot:75, pRat_freeThrow:68, pRat_offIQ:91, pRat_speed:90, pRat_strength:94, pRat_jumping:85, pRat_stamina:98, pRat_durability:91, pRat_dunking:95, pRat_andOne:97, pRat_passing:84, pRat_ballHandle:87, pRat_defIQ:90, pRat_intDef:92, pRat_perDef:92, pRat_steal:80, pRat_block:82, pRat_helpDef:96, pRat_offRebound:75, pRat_defRebound:92},
    {name:'Horace Grant',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:76,pRat_closeShot:81, pRat_midShot:84, pRat_longShot:50, pRat_freeThrow:71, pRat_offIQ:85, pRat_speed:76, pRat_strength:88, pRat_jumping:60, pRat_stamina:90, pRat_durability:86, pRat_dunking:88, pRat_andOne:68, pRat_passing:65, pRat_ballHandle:50, pRat_defIQ:94, pRat_intDef:93, pRat_perDef:75, pRat_steal:85, pRat_block:85, pRat_helpDef:88, pRat_offRebound:92, pRat_defRebound:94},
    {name:'Zach Lavine',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:89,pRat_offOverall:87,pRat_closeShot:87, pRat_midShot:82, pRat_longShot:85, pRat_freeThrow:85, pRat_offIQ:92, pRat_speed:84, pRat_strength:44, pRat_jumping:97, pRat_stamina:98, pRat_durability:83, pRat_dunking:95, pRat_andOne:94, pRat_passing:79, pRat_ballHandle:87, pRat_defIQ:53, pRat_intDef:49, pRat_perDef:65, pRat_steal:35, pRat_block:47, pRat_helpDef:64, pRat_offRebound:30, pRat_defRebound:62},
    {name:'Lebron James',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:94,pRat_offOverall:87,pRat_closeShot:94, pRat_midShot:86, pRat_longShot:82, pRat_freeThrow:77, pRat_offIQ:98, pRat_speed:87, pRat_strength:89, pRat_jumping:89, pRat_stamina:99, pRat_durability:97, pRat_dunking:90, pRat_andOne:95, pRat_passing:90, pRat_ballHandle:87, pRat_defIQ:82, pRat_intDef:82, pRat_perDef:89, pRat_steal:75, pRat_block:70, pRat_helpDef:90, pRat_offRebound:65, pRat_defRebound:75},
    {name:'Marcus Smart',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:75,pRat_offOverall:74,pRat_closeShot:89, pRat_midShot:68, pRat_longShot:72, pRat_freeThrow:76, pRat_offIQ:65, pRat_speed:75, pRat_strength:73, pRat_jumping:83, pRat_stamina:89, pRat_durability:83, pRat_dunking:50, pRat_andOne:50, pRat_passing:75, pRat_ballHandle:80, pRat_defIQ:83, pRat_intDef:74, pRat_perDef:93, pRat_steal:90, pRat_block:45, pRat_helpDef:90, pRat_offRebound:50, pRat_defRebound:51},
    {name:'Khris Middleton',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:82,pRat_closeShot:75, pRat_midShot:83, pRat_longShot:87, pRat_freeThrow:88, pRat_offIQ:80, pRat_speed:71, pRat_strength:73, pRat_jumping:66, pRat_stamina:92, pRat_durability:90, pRat_dunking:65, pRat_andOne:65, pRat_passing:78, pRat_ballHandle:77, pRat_defIQ:72, pRat_intDef:72, pRat_perDef:85, pRat_steal:50, pRat_block:50, pRat_helpDef:83, pRat_offRebound:50, pRat_defRebound:65},
    {name:'Nikola Vucevic',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:76,pRat_closeShot:84, pRat_midShot:79, pRat_longShot:77, pRat_freeThrow:64, pRat_offIQ:80, pRat_speed:62, pRat_strength:89, pRat_jumping:50, pRat_stamina:95, pRat_durability:77, pRat_dunking:65, pRat_andOne:64, pRat_passing:72, pRat_ballHandle:50, pRat_defIQ:58, pRat_intDef:74, pRat_perDef:50, pRat_steal:50, pRat_block:70, pRat_helpDef:73, pRat_offRebound:57, pRat_defRebound:93},
    {name:'Harrison Barnes',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:81,pRat_closeShot:75, pRat_midShot:82, pRat_longShot:84, pRat_freeThrow:84, pRat_offIQ:80, pRat_speed:77, pRat_strength:70, pRat_jumping:95, pRat_stamina:92, pRat_durability:82, pRat_dunking:81, pRat_andOne:60, pRat_passing:72, pRat_ballHandle:78, pRat_defIQ:60, pRat_intDef:67, pRat_perDef:75, pRat_steal:50, pRat_block:37, pRat_helpDef:65, pRat_offRebound:50, pRat_defRebound:66},
    {name:'Goran Dragic',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:72,pRat_offOverall:76,pRat_closeShot:77, pRat_midShot:77, pRat_longShot:75, pRat_freeThrow:83, pRat_offIQ:70, pRat_speed:76, pRat_strength:50, pRat_jumping:72, pRat_stamina:92, pRat_durability:84, pRat_dunking:50, pRat_andOne:79, pRat_passing:80, pRat_ballHandle:86, pRat_defIQ:63, pRat_intDef:50, pRat_perDef:73, pRat_steal:59, pRat_block:51, pRat_helpDef:74, pRat_offRebound:50, pRat_defRebound:64},
    {name:'Kyle Lowry',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:82,pRat_offOverall:82,pRat_closeShot:92, pRat_midShot:81, pRat_longShot:80, pRat_freeThrow:88, pRat_offIQ:89, pRat_speed:84, pRat_strength:67, pRat_jumping:72, pRat_stamina:96, pRat_durability:79, pRat_dunking:50, pRat_andOne:50, pRat_passing:88, pRat_ballHandle:86, pRat_defIQ:74, pRat_intDef:68, pRat_perDef:86, pRat_steal:82, pRat_block:51, pRat_helpDef:86, pRat_offRebound:50, pRat_defRebound:56},
    {name:'Steven Adams',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:76,pRat_offOverall:59,pRat_closeShot:65, pRat_midShot:65, pRat_longShot:50, pRat_freeThrow:57, pRat_offIQ:60, pRat_speed:60, pRat_strength:90, pRat_jumping:68, pRat_stamina:88, pRat_durability:82, pRat_dunking:75, pRat_andOne:54, pRat_passing:69, pRat_ballHandle:50, pRat_defIQ:69, pRat_intDef:82, pRat_perDef:55, pRat_steal:50, pRat_block:61, pRat_helpDef:85, pRat_offRebound:94, pRat_defRebound:85},
    {name:'Kevin Huerter',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:76,pRat_closeShot:82, pRat_midShot:73, pRat_longShot:82, pRat_freeThrow:79, pRat_offIQ:80, pRat_speed:84, pRat_strength:50, pRat_jumping:75, pRat_stamina:85, pRat_durability:83, pRat_dunking:65, pRat_andOne:50, pRat_passing:74, pRat_ballHandle:76, pRat_defIQ:53, pRat_intDef:50, pRat_perDef:64, pRat_steal:50, pRat_block:50, pRat_helpDef:63, pRat_offRebound:50, pRat_defRebound:54}
]



//Team Two

newYorkKnicks.roster = [
    {name:'Patrick Beverly',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:75,pRat_offOverall:70,pRat_closeShot:84, pRat_midShot:50, pRat_longShot:74, pRat_freeThrow:73, pRat_offIQ:70, pRat_speed:76, pRat_strength:60, pRat_jumping:91, pRat_stamina:90, pRat_durability:78, pRat_dunking:50, pRat_andOne:50, pRat_passing:75, pRat_ballHandle:78, pRat_defIQ:78, pRat_intDef:70, pRat_perDef:90, pRat_steal:56, pRat_block:72, pRat_helpDef:86, pRat_offRebound:50, pRat_defRebound:60},
    {name:'LaMelo Ball',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:82,pRat_offOverall:83,pRat_closeShot:78, pRat_midShot:76, pRat_longShot:83, pRat_freeThrow:88, pRat_offIQ:90, pRat_speed:84, pRat_strength:50, pRat_jumping:79, pRat_stamina:91, pRat_durability:82, pRat_dunking:65, pRat_andOne:80, pRat_passing:90, pRat_ballHandle:86, pRat_defIQ:73, pRat_intDef:50, pRat_perDef:79, pRat_steal:82, pRat_block:52, pRat_helpDef:79, pRat_offRebound:50, pRat_defRebound:75},
    {name:'Draymond Green',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:90,pRat_offOverall:69,pRat_closeShot:95, pRat_midShot:60, pRat_longShot:73, pRat_freeThrow:59, pRat_offIQ:89, pRat_speed:73, pRat_strength:85, pRat_jumping:66, pRat_stamina:85, pRat_durability:88, pRat_dunking:65, pRat_andOne:50, pRat_passing:86, pRat_ballHandle:78, pRat_defIQ:85, pRat_intDef:92, pRat_perDef:86, pRat_steal:70, pRat_block:78, pRat_helpDef:93, pRat_offRebound:50, pRat_defRebound:82},
    {name:'Devin Booker',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:88,pRat_offOverall:88,pRat_closeShot:86, pRat_midShot:90, pRat_longShot:87, pRat_freeThrow:86, pRat_offIQ:95, pRat_speed:79, pRat_strength:50, pRat_jumping:74, pRat_stamina:95, pRat_durability:81, pRat_dunking:75, pRat_andOne:91, pRat_passing:83, pRat_ballHandle:87, pRat_defIQ:58, pRat_intDef:50, pRat_perDef:74, pRat_steal:50, pRat_block:50, pRat_helpDef:65, pRat_offRebound:50, pRat_defRebound:62},
    {name:'Matisse Thybulle',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:77,pRat_offOverall:60,pRat_closeShot:65, pRat_midShot:48, pRat_longShot:70, pRat_freeThrow:60, pRat_offIQ:60, pRat_speed:76, pRat_strength:59, pRat_jumping:70, pRat_stamina:85, pRat_durability:80, pRat_dunking:70, pRat_andOne:50, pRat_passing:55, pRat_ballHandle:65, pRat_defIQ:86, pRat_intDef:75, pRat_perDef:89, pRat_steal:97, pRat_block:80, pRat_helpDef:88, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Bam Adebayo',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:89,pRat_offOverall:74,pRat_closeShot:84, pRat_midShot:85, pRat_longShot:69, pRat_freeThrow:76, pRat_offIQ:60, pRat_speed:74, pRat_strength:85, pRat_jumping:83, pRat_stamina:92, pRat_durability:90, pRat_dunking:80, pRat_andOne:84, pRat_passing:72, pRat_ballHandle:69, pRat_defIQ:80, pRat_intDef:92, pRat_perDef:79, pRat_steal:63, pRat_block:70, pRat_helpDef:92, pRat_offRebound:65, pRat_defRebound:89},
    {name:'Evan Fournier',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:80,pRat_closeShot:88, pRat_midShot:74, pRat_longShot:83, pRat_freeThrow:79, pRat_offIQ:80, pRat_speed:71, pRat_strength:50, pRat_jumping:63, pRat_stamina:95, pRat_durability:86, pRat_dunking:50, pRat_andOne:66, pRat_passing:75, pRat_ballHandle:82, pRat_defIQ:59, pRat_intDef:50, pRat_perDef:69, pRat_steal:50, pRat_block:50, pRat_helpDef:70, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Eric Gordon',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:78,pRat_offOverall:76,pRat_closeShot:78, pRat_midShot:72, pRat_longShot:87, pRat_freeThrow:72, pRat_offIQ:75, pRat_speed:79, pRat_strength:60, pRat_jumping:82, pRat_stamina:92, pRat_durability:78, pRat_dunking:70, pRat_andOne:74, pRat_passing:69, pRat_ballHandle:79, pRat_defIQ:60, pRat_intDef:50, pRat_perDef:78, pRat_steal:50, pRat_block:55, pRat_helpDef:73, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Boban Marjanović',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:72,pRat_offOverall:73,pRat_closeShot:83, pRat_midShot:70, pRat_longShot:63, pRat_freeThrow:77, pRat_offIQ:75, pRat_speed:50, pRat_strength:71, pRat_jumping:50, pRat_stamina:70, pRat_durability:65, pRat_dunking:60, pRat_andOne:70, pRat_passing:55, pRat_ballHandle:50, pRat_defIQ:54, pRat_intDef:73, pRat_perDef:50, pRat_steal:50, pRat_block:61, pRat_helpDef:65, pRat_offRebound:83, pRat_defRebound:84},
    {name:'Jerami Grant',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:84,pRat_offOverall:78,pRat_closeShot:75, pRat_midShot:77, pRat_longShot:76, pRat_freeThrow:85, pRat_offIQ:80, pRat_speed:73, pRat_strength:72, pRat_jumping:84, pRat_stamina:95, pRat_durability:82, pRat_dunking:89, pRat_andOne:93, pRat_passing:69, pRat_ballHandle:76, pRat_defIQ:70, pRat_intDef:70, pRat_perDef:69, pRat_steal:50, pRat_block:71, pRat_helpDef:77, pRat_offRebound:50, pRat_defRebound:60},
    {name:'Kelly Olynyk',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:71,pRat_offOverall:77,pRat_closeShot:80, pRat_midShot:71, pRat_longShot:77, pRat_freeThrow:60, pRat_offIQ:98, pRat_speed:50, pRat_strength:70, pRat_jumping:55, pRat_stamina:89, pRat_durability:82, pRat_dunking:60, pRat_andOne:79, pRat_passing:60, pRat_ballHandle:50, pRat_defIQ:59, pRat_intDef:70, pRat_perDef:50, pRat_steal:73, pRat_block:67, pRat_helpDef:66, pRat_offRebound:53, pRat_defRebound:79}
]


freeAgents.roster = [
    {name:'Giannis Antetokounmpo',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:95,pRat_offOverall:86,pRat_closeShot:95, pRat_midShot:83, pRat_longShot:75, pRat_freeThrow:68, pRat_offIQ:91, pRat_speed:90, pRat_strength:94, pRat_jumping:85, pRat_stamina:98, pRat_durability:91, pRat_dunking:95, pRat_andOne:97, pRat_passing:84, pRat_ballHandle:87, pRat_defIQ:90, pRat_intDef:92, pRat_perDef:92, pRat_steal:80, pRat_block:82, pRat_helpDef:96, pRat_offRebound:75, pRat_defRebound:92},
    {name:'Horace Grant',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:76,pRat_closeShot:81, pRat_midShot:84, pRat_longShot:50, pRat_freeThrow:71, pRat_offIQ:85, pRat_speed:76, pRat_strength:88, pRat_jumping:60, pRat_stamina:90, pRat_durability:86, pRat_dunking:88, pRat_andOne:68, pRat_passing:65, pRat_ballHandle:50, pRat_defIQ:94, pRat_intDef:93, pRat_perDef:75, pRat_steal:85, pRat_block:85, pRat_helpDef:88, pRat_offRebound:92, pRat_defRebound:94},
    {name:'Zach Lavine',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:89,pRat_offOverall:87,pRat_closeShot:87, pRat_midShot:82, pRat_longShot:85, pRat_freeThrow:85, pRat_offIQ:92, pRat_speed:84, pRat_strength:44, pRat_jumping:97, pRat_stamina:98, pRat_durability:83, pRat_dunking:95, pRat_andOne:94, pRat_passing:79, pRat_ballHandle:87, pRat_defIQ:53, pRat_intDef:49, pRat_perDef:65, pRat_steal:35, pRat_block:47, pRat_helpDef:64, pRat_offRebound:30, pRat_defRebound:62},
    {name:'Lebron James',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:94,pRat_offOverall:87,pRat_closeShot:94, pRat_midShot:86, pRat_longShot:82, pRat_freeThrow:77, pRat_offIQ:98, pRat_speed:87, pRat_strength:89, pRat_jumping:89, pRat_stamina:99, pRat_durability:97, pRat_dunking:90, pRat_andOne:95, pRat_passing:90, pRat_ballHandle:87, pRat_defIQ:82, pRat_intDef:82, pRat_perDef:89, pRat_steal:75, pRat_block:70, pRat_helpDef:90, pRat_offRebound:65, pRat_defRebound:75},
    {name:'Marcus Smart',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:75,pRat_offOverall:74,pRat_closeShot:89, pRat_midShot:68, pRat_longShot:72, pRat_freeThrow:76, pRat_offIQ:65, pRat_speed:75, pRat_strength:73, pRat_jumping:83, pRat_stamina:89, pRat_durability:83, pRat_dunking:50, pRat_andOne:50, pRat_passing:75, pRat_ballHandle:80, pRat_defIQ:83, pRat_intDef:74, pRat_perDef:93, pRat_steal:90, pRat_block:45, pRat_helpDef:90, pRat_offRebound:50, pRat_defRebound:51},
    {name:'Khris Middleton',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:82,pRat_closeShot:75, pRat_midShot:83, pRat_longShot:87, pRat_freeThrow:88, pRat_offIQ:80, pRat_speed:71, pRat_strength:73, pRat_jumping:66, pRat_stamina:92, pRat_durability:90, pRat_dunking:65, pRat_andOne:65, pRat_passing:78, pRat_ballHandle:77, pRat_defIQ:72, pRat_intDef:72, pRat_perDef:85, pRat_steal:50, pRat_block:50, pRat_helpDef:83, pRat_offRebound:50, pRat_defRebound:65},
    {name:'Nikola Vucevic',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:85,pRat_offOverall:76,pRat_closeShot:84, pRat_midShot:79, pRat_longShot:77, pRat_freeThrow:64, pRat_offIQ:80, pRat_speed:62, pRat_strength:89, pRat_jumping:50, pRat_stamina:95, pRat_durability:77, pRat_dunking:65, pRat_andOne:64, pRat_passing:72, pRat_ballHandle:50, pRat_defIQ:58, pRat_intDef:74, pRat_perDef:50, pRat_steal:50, pRat_block:70, pRat_helpDef:73, pRat_offRebound:57, pRat_defRebound:93},
    {name:'Harrison Barnes',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:81,pRat_closeShot:75, pRat_midShot:82, pRat_longShot:84, pRat_freeThrow:84, pRat_offIQ:80, pRat_speed:77, pRat_strength:70, pRat_jumping:95, pRat_stamina:92, pRat_durability:82, pRat_dunking:81, pRat_andOne:60, pRat_passing:72, pRat_ballHandle:78, pRat_defIQ:60, pRat_intDef:67, pRat_perDef:75, pRat_steal:50, pRat_block:37, pRat_helpDef:65, pRat_offRebound:50, pRat_defRebound:66},
    {name:'Goran Dragic',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:72,pRat_offOverall:76,pRat_closeShot:77, pRat_midShot:77, pRat_longShot:75, pRat_freeThrow:83, pRat_offIQ:70, pRat_speed:76, pRat_strength:50, pRat_jumping:72, pRat_stamina:92, pRat_durability:84, pRat_dunking:50, pRat_andOne:79, pRat_passing:80, pRat_ballHandle:86, pRat_defIQ:63, pRat_intDef:50, pRat_perDef:73, pRat_steal:59, pRat_block:51, pRat_helpDef:74, pRat_offRebound:50, pRat_defRebound:64},
    {name:'Kyle Lowry',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:82,pRat_offOverall:82,pRat_closeShot:92, pRat_midShot:81, pRat_longShot:80, pRat_freeThrow:88, pRat_offIQ:89, pRat_speed:84, pRat_strength:67, pRat_jumping:72, pRat_stamina:96, pRat_durability:79, pRat_dunking:50, pRat_andOne:50, pRat_passing:88, pRat_ballHandle:86, pRat_defIQ:74, pRat_intDef:68, pRat_perDef:86, pRat_steal:82, pRat_block:51, pRat_helpDef:86, pRat_offRebound:50, pRat_defRebound:56},
    {name:'Steven Adams',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:76,pRat_offOverall:59,pRat_closeShot:65, pRat_midShot:65, pRat_longShot:50, pRat_freeThrow:57, pRat_offIQ:60, pRat_speed:60, pRat_strength:90, pRat_jumping:68, pRat_stamina:88, pRat_durability:82, pRat_dunking:75, pRat_andOne:54, pRat_passing:69, pRat_ballHandle:50, pRat_defIQ:69, pRat_intDef:82, pRat_perDef:55, pRat_steal:50, pRat_block:61, pRat_helpDef:85, pRat_offRebound:94, pRat_defRebound:85},
    {name:'Kevin Huerter',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:76,pRat_closeShot:82, pRat_midShot:73, pRat_longShot:82, pRat_freeThrow:79, pRat_offIQ:80, pRat_speed:84, pRat_strength:50, pRat_jumping:75, pRat_stamina:85, pRat_durability:83, pRat_dunking:65, pRat_andOne:50, pRat_passing:74, pRat_ballHandle:76, pRat_defIQ:53, pRat_intDef:50, pRat_perDef:64, pRat_steal:50, pRat_block:50, pRat_helpDef:63, pRat_offRebound:50, pRat_defRebound:54},
    {name:'Patrick Beverly',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:75,pRat_offOverall:70,pRat_closeShot:84, pRat_midShot:50, pRat_longShot:74, pRat_freeThrow:73, pRat_offIQ:70, pRat_speed:76, pRat_strength:60, pRat_jumping:91, pRat_stamina:90, pRat_durability:78, pRat_dunking:50, pRat_andOne:50, pRat_passing:75, pRat_ballHandle:78, pRat_defIQ:78, pRat_intDef:70, pRat_perDef:90, pRat_steal:56, pRat_block:72, pRat_helpDef:86, pRat_offRebound:50, pRat_defRebound:60},
    {name:'LaMelo Ball',position:'PG',positionName:'Point Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:82,pRat_offOverall:83,pRat_closeShot:78, pRat_midShot:76, pRat_longShot:83, pRat_freeThrow:88, pRat_offIQ:90, pRat_speed:84, pRat_strength:50, pRat_jumping:79, pRat_stamina:91, pRat_durability:82, pRat_dunking:65, pRat_andOne:80, pRat_passing:90, pRat_ballHandle:86, pRat_defIQ:73, pRat_intDef:50, pRat_perDef:79, pRat_steal:82, pRat_block:52, pRat_helpDef:79, pRat_offRebound:50, pRat_defRebound:75},
    {name:'Draymond Green',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:90,pRat_offOverall:69,pRat_closeShot:95, pRat_midShot:60, pRat_longShot:73, pRat_freeThrow:59, pRat_offIQ:89, pRat_speed:73, pRat_strength:85, pRat_jumping:66, pRat_stamina:85, pRat_durability:88, pRat_dunking:65, pRat_andOne:50, pRat_passing:86, pRat_ballHandle:78, pRat_defIQ:85, pRat_intDef:92, pRat_perDef:86, pRat_steal:70, pRat_block:78, pRat_helpDef:93, pRat_offRebound:50, pRat_defRebound:82},
    {name:'Devin Booker',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:88,pRat_offOverall:88,pRat_closeShot:86, pRat_midShot:90, pRat_longShot:87, pRat_freeThrow:86, pRat_offIQ:95, pRat_speed:79, pRat_strength:50, pRat_jumping:74, pRat_stamina:95, pRat_durability:81, pRat_dunking:75, pRat_andOne:91, pRat_passing:83, pRat_ballHandle:87, pRat_defIQ:58, pRat_intDef:50, pRat_perDef:74, pRat_steal:50, pRat_block:50, pRat_helpDef:65, pRat_offRebound:50, pRat_defRebound:62},
    {name:'Matisse Thybulle',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:77,pRat_offOverall:60,pRat_closeShot:65, pRat_midShot:48, pRat_longShot:70, pRat_freeThrow:60, pRat_offIQ:60, pRat_speed:76, pRat_strength:59, pRat_jumping:70, pRat_stamina:85, pRat_durability:80, pRat_dunking:70, pRat_andOne:50, pRat_passing:55, pRat_ballHandle:65, pRat_defIQ:86, pRat_intDef:75, pRat_perDef:89, pRat_steal:97, pRat_block:80, pRat_helpDef:88, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Bam Adebayo',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:89,pRat_offOverall:74,pRat_closeShot:84, pRat_midShot:85, pRat_longShot:69, pRat_freeThrow:76, pRat_offIQ:60, pRat_speed:74, pRat_strength:85, pRat_jumping:83, pRat_stamina:92, pRat_durability:90, pRat_dunking:80, pRat_andOne:84, pRat_passing:72, pRat_ballHandle:69, pRat_defIQ:80, pRat_intDef:92, pRat_perDef:79, pRat_steal:63, pRat_block:70, pRat_helpDef:92, pRat_offRebound:65, pRat_defRebound:89},
    {name:'Evan Fournier',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:73,pRat_offOverall:80,pRat_closeShot:88, pRat_midShot:74, pRat_longShot:83, pRat_freeThrow:79, pRat_offIQ:80, pRat_speed:71, pRat_strength:50, pRat_jumping:63, pRat_stamina:95, pRat_durability:86, pRat_dunking:50, pRat_andOne:66, pRat_passing:75, pRat_ballHandle:82, pRat_defIQ:59, pRat_intDef:50, pRat_perDef:69, pRat_steal:50, pRat_block:50, pRat_helpDef:70, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Eric Gordon',position:'SG',positionName:'Shooting Guard',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:78,pRat_offOverall:76,pRat_closeShot:78, pRat_midShot:72, pRat_longShot:87, pRat_freeThrow:72, pRat_offIQ:75, pRat_speed:79, pRat_strength:60, pRat_jumping:82, pRat_stamina:92, pRat_durability:78, pRat_dunking:70, pRat_andOne:74, pRat_passing:69, pRat_ballHandle:79, pRat_defIQ:60, pRat_intDef:50, pRat_perDef:78, pRat_steal:50, pRat_block:55, pRat_helpDef:73, pRat_offRebound:50, pRat_defRebound:50},
    {name:'Boban Marjanović',position:'C',positionName:'Center',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:72,pRat_offOverall:73,pRat_closeShot:83, pRat_midShot:70, pRat_longShot:63, pRat_freeThrow:77, pRat_offIQ:75, pRat_speed:50, pRat_strength:71, pRat_jumping:50, pRat_stamina:70, pRat_durability:65, pRat_dunking:60, pRat_andOne:70, pRat_passing:55, pRat_ballHandle:50, pRat_defIQ:54, pRat_intDef:73, pRat_perDef:50, pRat_steal:50, pRat_block:61, pRat_helpDef:65, pRat_offRebound:83, pRat_defRebound:84},
    {name:'Jerami Grant',position:'SF',positionName:'Small Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:84,pRat_offOverall:78,pRat_closeShot:75, pRat_midShot:77, pRat_longShot:76, pRat_freeThrow:85, pRat_offIQ:80, pRat_speed:73, pRat_strength:72, pRat_jumping:84, pRat_stamina:95, pRat_durability:82, pRat_dunking:89, pRat_andOne:93, pRat_passing:69, pRat_ballHandle:76, pRat_defIQ:70, pRat_intDef:70, pRat_perDef:69, pRat_steal:50, pRat_block:71, pRat_helpDef:77, pRat_offRebound:50, pRat_defRebound:60},
    {name:'Kelly Olynyk',position:'PF',positionName:'Power Forward',boxScore:{points:0,assists:0,rebounds:0,steals:0,blocks:0,FG:0,FGA:0,fouls:0,FT:0,FTA:0,TP:0,TPA:0,TO:0,minutes:0},benchStatus:'bench',inactive:'n',fatigue:1,pRat_overall:71,pRat_offOverall:77,pRat_closeShot:80, pRat_midShot:71, pRat_longShot:77, pRat_freeThrow:60, pRat_offIQ:98, pRat_speed:50, pRat_strength:70, pRat_jumping:55, pRat_stamina:89, pRat_durability:82, pRat_dunking:60, pRat_andOne:79, pRat_passing:60, pRat_ballHandle:50, pRat_defIQ:59, pRat_intDef:70, pRat_perDef:50, pRat_steal:73, pRat_block:67, pRat_helpDef:66, pRat_offRebound:53, pRat_defRebound:79}

]






